### ISSUE TITLE
Repetitions should be independent 

### ISSUE THREAD

**Issue by DanielKneipp** [h3ct0r/StarcraftNash#9]
The objects of the players are reused from one repetition to another. These objects should be destroyed and recreated to ensure that no knowledge obtained in one repetition will be used in another.

**Comment by h3ct0r** [comment]
Hi Daniel, if you have a working version with that enhancement you can submit a pull request!
It will be very welcome!

**Comment by andertavares** [comment]
Hector, Daniel is working with our project for this year's AI course

We'll receive a pull request with his "strategy selectors" soon :)

This issue is about a behavior we observed on the engine that persists
players between experiment repetitions, which should not happen.

--
Anderson Rocha Tavares
http://dcc.ufmg.br/~anderson

2016-12-03 1:04 GMT-02:00 Héctor A. <notifications@github.com>:

**Comment by h3ct0r** [comment]
Cool!, Welcome @DanielKneipp :)
Yes @andertavares I was talking about that too: if Daniel has already a patch for it, send it over. If not, we will look into it, it must be a simple fix.

**Comment by DanielKneipp** [comment]
Thank you, @h3ct0r :D
I don't have a patch yet but you can leave this with me. I'll fix it soon.

**Comment by andertavares** [comment]
Fixed by @DanielKneipp in 46a43c6. Thanks! :D
